[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fictional-couscous"
version = "0.1.0"
description = "A Python package for neo4j based graphrag knowledge-base"
readme = "README.md"
authors = [
    {name = "Tom Xu", email = "xut565883@gmail.com"},
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = [
    "neo4j>=5.28.1",
    "openai>=1.69.0"
]

[project.urls]
"Homepage" = "https://github.com/xxl4tomxu98/my_package"
"Bug Tracker" = "https://github.com/xxl4tomxu98/my_package/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/fictional-couscous"]